import type { DailyScan, Lead, Profile } from "./types";

export const DEFAULT_PROFILE: Profile = {
  id: "3d-designer-uae",
  name: "3D Designer Jobs (UAE)",
  slug: "3d-designer-uae",
  description:
    "UAE hiring pipeline for 3D designer, creative director, events, exhibition, and spatial design roles.",
  icp_keywords: [
    "3D designer",
    "creative director",
    "art director",
    "events",
    "exhibition",
    "spatial design",
    "Unreal Engine",
    "Dubai",
    "Abu Dhabi",
  ],
  scan_queries: [
    "site:linkedin.com hiring 3d designer OR 3d artist dubai uae freelance 2026",
    "site:linkedin.com creative director OR art director events hiring dubai 2026",
    "site:linkedin.com freelance 3D dubai event exhibition designer artist",
    "site:linkedin.com/jobs 3d designer OR 3d artist OR CG generalist dubai 2026",
    "site:linkedin.com/jobs creative director OR art director dubai events 2026",
    "dubai creative director OR art director hiring 3D OR CG freelance events 2026",
    "uae 3D designer OR 3D artist event exhibition freelance hiring 2026",
  ],
  message_templates: {
    linkedin: `Hey {name},

Saw your post about looking for a {role_seeking} at {company}.
I'm Black, Creative Technology & CG Director at unreal.ae in Dubai.
I specialize in real-time 3D, Unreal Engine, and experiential design for events and exhibitions.

Portfolio (pw: 2403): {portfolio_url}
CV/PDF: {pdf_url}

Would love to chat if you're still looking. Available for freelance and project-based work.

Best,
Black`,
    email: `Subject: 3D/CG Designer - Saw your post about {role_seeking}

Hi {name},

I came across your post looking for a {role_seeking} at {company}.

I'm Black, Creative Technology & CG Director at unreal.ae in Dubai.
I specialize in real-time 3D, Unreal Engine, and experiential design for events, exhibitions, and brand experiences.

Portfolio (password: 2403): {portfolio_url}
Full CV/PDF: {pdf_url}

I'm available for freelance and project-based engagements.
Would love to connect and see if there's a fit.

Best,
Black
unreal.ae`,
    whatsapp:
      "Hey {name}, saw your post about looking for a {role_seeking} at {company}. I'm Black, Creative Technology & CG Director at unreal.ae in Dubai. I specialize in real-time 3D and Unreal Engine for events and exhibitions. Portfolio (pw: 2403): {portfolio_url}. CV: {pdf_url}. Available for freelance work if useful.",
    instagram:
      "Hey {name}, saw your post about {role_seeking}. I'm Black from unreal.ae Dubai — real-time 3D, Unreal Engine, events & exhibitions. Portfolio (pw: 2403): {portfolio_url}. CV: {pdf_url}. Available for freelance — would love to connect.",
  },
  portfolio_url: "https://black-portfolio-chi.vercel.app/",
  pdf_url: "https://drive.google.com/file/d/19KjA5-J_v2b9OfJgYVKnJfVTF0m-pp35/view?usp=sharing",
  accent_color: "#3ecf8e",
  created_at: "2026-06-17T08:00:00Z",
  is_active: true,
};

export const CEO_EXPANSION_PROFILE: Profile = {
  id: "ceo-expansion-gcc",
  name: "CEO Expansion Leads (GCC)",
  slug: "ceo-expansion-gcc",
  description:
    "Mid-size company CEOs in GCC who are expanding teams or restructuring — target for creative technology and spatial design consulting.",
  icp_keywords: [
    "CEO", "Managing Director", "Founder", "expansion", "restructuring",
    "mid-size", "SME", "GCC", "Dubai", "Riyadh", "Abu Dhabi", "Doha",
  ],
  scan_queries: [
    'site:linkedin.com/posts "expanding our team" OR "growing our team" CEO OR "managing director" OR founder dubai OR riyadh 2026',
    'site:linkedin.com/posts "restructuring" OR "new division" OR "scaling up" CEO OR founder mid-size UAE OR KSA OR qatar 2026',
    'site:linkedin.com/posts "hiring" CEO OR "managing director" OR "head of" dubai OR riyadh expansion OR growth 2026',
    'GCC mid-size company CEO expansion restructuring hiring team dubai riyadh 2026',
  ],
  message_templates: {
    linkedin: `Hi {name},

I noticed {company} is in a growth phase and expanding the team.

I'm Black, Creative Technology & CG Director at unreal.ae in Dubai. I help mid-size companies optimize their spatial design, real-time 3D, and creative technology workflows as they scale.

Portfolio (pw: 2403): {portfolio_url}
CV: {pdf_url}

Would love to explore how we could support your expansion.

Best,
Black`,
    email: `Subject: Creative technology support for {company}

Hi {name},

Noticed {company} is expanding — exciting phase.

I'm Black, Creative Technology & CG Director at unreal.ae in Dubai. I specialize in real-time 3D, Unreal Engine, and spatial design for mid-size companies scaling across GCC.

Portfolio (password: 2403): {portfolio_url}
Full CV/PDF: {pdf_url}

Open to a call to explore how we could support your team's growth.

Best,
Black
unreal.ae`,
    whatsapp:
      "Hi {name}, saw {company} is expanding. I'm Black from unreal.ae Dubai — creative tech & spatial design for mid-size companies scaling up. Portfolio (pw: 2403): {portfolio_url}. CV: {pdf_url}. Worth a chat?",
    instagram:
      "Hi {name}, saw {company} is growing. I'm Black from unreal.ae Dubai — creative tech partner for mid-size companies in GCC. Portfolio (pw: 2403): {portfolio_url}.",
  },
  portfolio_url: "https://black-portfolio-chi.vercel.app/",
  pdf_url: "https://drive.google.com/file/d/19KjA5-J_v2b9OfJgYVKnJfVTF0m-pp35/view?usp=sharing",
  accent_color: "#8B5CF6",
  created_at: "2026-06-18T00:00:00Z",
  is_active: true,
};

export const SEED_PROFILES: Profile[] = [DEFAULT_PROFILE, CEO_EXPANSION_PROFILE];

const RAW_VAULT_LEADS: Omit<Lead, "profile_id" | "profile_slug">[] = [
  {
    id: 1,
    name: "Gabriel Raphael Chetty",
    title: "Recruiter",
    company: "Kingston Stanley",
    role_seeking: "Senior 3D Designer - Exhibitions & Events",
    location: "Abu Dhabi",
    post_url:
      "https://www.linkedin.com/posts/gabriel-raphael-chetty_senior-3d-designer-exhibitions-events-activity-7470097886966558720-OqSj",
    post_date: "2026-06-14",
    salary: "AED 17,000 - 20,000",
    source: "LinkedIn Post",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: "gabriel-raphael-chetty",
    channels_available: ["linkedin"],
    status: "new",
    rating: 5,
    notes:
      "Direct recruiter. Freelance option, own visa. Also hiring Creative Director (Events) + Lead 3D Designer. Best lead in the pipeline.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 2,
    name: "Andre Matarazzo",
    title: "3D Artist / Motion Designer",
    company: "DDB Dubai",
    role_seeking: "Designer (3D/Motion)",
    location: "Dubai",
    post_url:
      "https://www.linkedin.com/posts/andrematarazzo_need-a-great-designer-to-join-the-team-if-activity-7469651564996063232-zymr",
    post_date: "2026-06-13",
    salary: null,
    source: "LinkedIn Post",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: "andrematarazzo",
    channels_available: ["linkedin"],
    status: "new",
    rating: 4,
    notes:
      "Personal post from DDB team member. DDB is major agency. Role is vague. Worth DMing Andre directly to clarify.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 3,
    name: "Mishel Tobin",
    title: "Founder",
    company: "Neon People (Recruitment)",
    role_seeking: "Freelance Senior 3D Designer + Creative Lead + 2D Designer",
    location: "Dubai",
    post_url:
      "https://www.linkedin.com/posts/misheltobin_thanks-for-getting-in-touch-due-to-an-activity-7462549449395892224-PNi1",
    post_date: "2026-06-08",
    salary: null,
    source: "LinkedIn Post",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: "misheltobin",
    channels_available: ["linkedin"],
    status: "new",
    rating: 5,
    notes:
      "Recruiter with 3 freelance creative roles for live events agency. Multiple opportunities from one contact.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 4,
    name: "Bethany Hitchmough",
    title: "Recruiter",
    company: "Discovered.ae",
    role_seeking: "Creative Director (3D - 3DS Max, C4D, SketchUp)",
    location: "Dubai",
    post_url: null,
    post_date: "2026-06-08",
    salary: null,
    source: "discovered.ae",
    contact_email: "bethany@discovered.ae",
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin", "email"],
    status: "new",
    rating: 5,
    notes:
      "Hottest lead. Agency is explicitly looking for someone who can build a reliable network of external 3D partners.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 5,
    name: "Anne Marie McAteer",
    title: "HR - Employee Experience MENA",
    company: "Pico Middle East",
    role_seeking: "Creative Director",
    location: "Dubai",
    post_url: null,
    post_date: "2026-06-07",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 4,
    notes: "Posted about 10 days ago. Experiential and exhibitions. Pico is a major player.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 6,
    name: "Kayalvizhi Jayakumar",
    title: "HR Leader",
    company: "UAE-based Company (Remote)",
    role_seeking: "Remote Freelance 3D Designer / Modeler",
    location: "Remote (UAE Company)",
    post_url:
      "https://www.linkedin.com/posts/kayalhrleader_looking-for-a-remote-freelance-3d-designer-activity-7458449303724826624-CkEh",
    post_date: "2026-05-25",
    salary: null,
    source: "LinkedIn Post",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: "kayalhrleader",
    channels_available: ["linkedin"],
    status: "new",
    rating: 3,
    notes: "Remote freelance, converting 2D CAD to 3D product renders.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 7,
    name: "Charli Wright",
    title: "Creative",
    company: "JWI",
    role_seeking: "Creative Art Director",
    location: "Dubai",
    post_url: "https://www.linkedin.com/posts/charliwright_hiring-activity-7443152322471542784-2YPm",
    post_date: "2026-04-20",
    salary: null,
    source: "LinkedIn Post",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: "charliwright",
    channels_available: ["linkedin"],
    status: "new",
    rating: 3,
    notes: "Premium brand clients. Art Director role, not specifically 3D but still relevant.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 8,
    name: "The Hanging House",
    title: "Agency",
    company: "The Hanging House",
    role_seeking: "Freelance 3D Designer",
    location: "Dubai",
    post_url: null,
    post_date: "2026-03-15",
    salary: null,
    source: "LinkedIn Job",
    contact_email: "joinus@thehanginghouse.com",
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin", "email"],
    status: "new",
    rating: 3,
    notes: "Experiential agency. Email available for direct outreach.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 9,
    name: "Cyberdrone Drone Shows",
    title: "Company",
    company: "Cyberdrone",
    role_seeking: "Lead CG Artist / Lead 3D Artist",
    location: "Dubai / Remote",
    post_url: "https://cyberdrone.applytojob.com",
    post_date: "2026-01-20",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 2,
    notes: "Drone show 3D models. Older posting.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 10,
    name: "Darcstudio",
    title: "Studio",
    company: "Darcstudio",
    role_seeking: "Lead 3D Artist - Unreal Engine",
    location: "Dubai",
    post_url: null,
    post_date: "2025-06-01",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 2,
    notes: "Unreal Engine focused. Strong fit, old posting.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 11,
    name: "Entourage Marketing & Events",
    title: "Agency",
    company: "Entourage Intl",
    role_seeking: "3D Designer",
    location: "Dubai",
    post_url: null,
    post_date: "2026-06-10",
    salary: null,
    source: "LinkedIn Job",
    contact_email: "info@entourageintl.com",
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin", "email"],
    status: "selected",
    rating: 4,
    notes: "Strategic storytelling and events agency. Immediate hiring.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 12,
    name: "Talent Blueprint FZ LLC",
    title: "Recruitment",
    company: "Talent Blueprint",
    role_seeking: "3D Designer (Events)",
    location: "Dubai",
    post_url: "https://www.linkedin.com/jobs/view/4294321932/",
    post_date: "2025-11-01",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 2,
    notes: "Freelance or project-based. Also recruiting Art Director roles.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 13,
    name: "Sundus Consultancy",
    title: "Recruitment",
    company: "Sundus",
    role_seeking: "Senior 3D Animator",
    location: "Dubai",
    post_url: null,
    post_date: "2026-05-01",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 3,
    notes: "Animation-focused role.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 14,
    name: "BINYAN Studios",
    title: "Studio",
    company: "BINYAN Studios",
    role_seeking: "3D Artist (Remote)",
    location: "Remote (London/Dubai)",
    post_url: null,
    post_date: "2026-04-01",
    salary: null,
    source: "LinkedIn Job",
    contact_email: "careers@binyanstudios.com",
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin", "email"],
    status: "new",
    rating: 3,
    notes: "Architectural visualization. Remote possible.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 15,
    name: "AVANTGARDE Group",
    title: "Agency",
    company: "AVANTGARDE",
    role_seeking: "Freelance Senior 3D Event & Exhibition Stand Designer",
    location: "Dubai",
    post_url:
      "https://www.linkedin.com/posts/avantgarde_avantgarde-dubai-is-hiring-we-are-looking-activity-7387087122576347136-Ch09",
    post_date: "2026-02-01",
    salary: null,
    source: "LinkedIn Post",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 3,
    notes: "Strong fit for 3D, events, exhibitions, and freelance work.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 16,
    name: "ESMOS Recruitment",
    title: "Recruitment",
    company: "ESMOS",
    role_seeking: "Associate Creative Director",
    location: "Dubai",
    post_url: null,
    post_date: "2026-05-15",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 3,
    notes: "Event services industry client. Could need 3D support.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 17,
    name: "Discovered MENA",
    title: "Recruitment",
    company: "Discovered MENA",
    role_seeking: "Art Director (Spatial Design)",
    location: "Dubai",
    post_url: null,
    post_date: "2026-03-01",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 3,
    notes: "Spatial design focus.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 18,
    name: "The Connected Co",
    title: "Recruitment",
    company: "The Connected Co",
    role_seeking: "Creative Director",
    location: "Dubai",
    post_url: null,
    post_date: "2026-06-01",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 4,
    notes: "3D disciplines mentioned in the job description.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 19,
    name: "Kingston Stanley",
    title: "Recruitment",
    company: "Kingston Stanley",
    role_seeking: "Creative Director",
    location: "Dubai",
    post_url: null,
    post_date: "2026-06-01",
    salary: null,
    source: "LinkedIn Job",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 3,
    notes: "Active posting. Same recruiter as Gabriel Chetty.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
  {
    id: 20,
    name: "Quill MENA",
    title: "Agency",
    company: "Quill MENA",
    role_seeking: "Events Creative Director",
    location: "Dubai",
    post_url: "https://quillmena.com",
    post_date: "2026-05-01",
    salary: null,
    source: "quillmena.com",
    contact_email: null,
    contact_phone: null,
    contact_linkedin: null,
    channels_available: ["linkedin"],
    status: "new",
    rating: 4,
    notes: "Experiential marketing focus. Direct company site application.",
    discovered_at: "2026-06-17T08:00:00Z",
    contacted_at: null,
    replied_at: null,
  },
];

export const VAULT_LEADS: Lead[] = RAW_VAULT_LEADS.map((lead) => ({
  ...lead,
  profile_id: DEFAULT_PROFILE.id,
  profile_slug: DEFAULT_PROFILE.slug,
}));

export const SEED_SCANS: DailyScan[] = [
  {
    id: 1,
    profile_id: DEFAULT_PROFILE.id,
    scan_date: "2026-06-17",
    leads_found: VAULT_LEADS.length,
    new_leads: VAULT_LEADS.filter((lead) => lead.status === "new").length,
    dms_sent: 0,
    replies_received: 0,
    status: "completed",
  },
];
